name: Deploy .NET Core to Somee

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy code về
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Cài đặt .NET 8
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # 3. Build code (Đã trỏ đúng thư mục proMvcApi)
    - name: Publish .NET App
      run: dotnet publish ./proMvcApi -c Release -o ./publish_output

    # 4. Cài đặt FTP
    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    # 5. Đẩy lên Server (Sử dụng Secrets)
    - name: Deploy via FTP
      run: |
        lftp -e "set ftp:ssl-allow no; open -u ${{ secrets.USER }},${{ secrets.PW }} ${{ secrets.HOST }}; mirror -R ./publish_output /www.MINHVY.somee.com; bye"
