name: Deploy HTML to Somee via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Somee Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST }}       # biến HOST
          username: ${{ secrets.USERNAME }} # biến USERNAME
          password: ${{ secrets.PW }}       # biến PW

          protocol: ftp
          local-dir: ./
          server-dir: /wwwroot/             # thư mục mặc định của Somee

          exclude: |
            **/.git*
            **/.github*
            **/node_modules*
            README.md
            LICENSE
